# Generated by Django 5.2.7 on 2025-10-13 18:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0004_alter_task_assignee_alter_task_completed_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='created_at',
            field=models.DateField(default=datetime.datetime(2025, 10, 13, 18, 4, 7, 611346)),
        ),
    ]
