# Generated by Django 5.2.7 on 2025-10-13 19:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0005_alter_task_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='created_at',
            field=models.DateField(default=datetime.datetime(2025, 10, 13, 19, 49, 21, 771440)),
        ),
    ]
