# Generated by Django 5.0 on 2025-11-11 08:29

import django.contrib.auth.password_validation
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auths', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='password',
            field=models.CharField(help_text="User's hash representation of the password", max_length=254, validators=[django.contrib.auth.password_validation.validate_password], verbose_name='Password'),
        ),
    ]
